<?php

namespace AppBundle\Repository;

/**
 * ArraytestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArraytestRepository extends \Doctrine\ORM\EntityRepository
{
}
