<?php

namespace AppBundle\Repository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTodos($id){
        $qb = $this->createQueryBuilder('td')
            ->select('td.id','td.status','td.name','td.description','td.dueDate','td.createdAt','td.status','td.category','td.priority')
//            ->groupBy('td.status');
            ->where('td.userId = :userid')
            ->orderBy('td.dueDate','asc')
            ->setParameter('userid',$id);
        $query = $qb->getQuery();

        return $query->execute();
    }
}
