<?php

namespace AppBundle\Repository;
use Doctrine\Common\Persistence\ManagerRegistry;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTodos($id,$page_num=0){

        $limit = 9;

        $qb = $this->createQueryBuilder('td')
            ->select('td.id','td.status','td.name','td.description','td.dueDate','td.createdAt','td.category','td.priority')
            ->where('td.userId = :userid')
            ->addOrderBy('td.status','asc')
            ->addOrderBy('td.dueDate','asc')
            ->setParameter('userid',$id)
            ->setFirstResult($page_num * $limit)
            ->setMaxResults($limit);
//        $query = $qb->getQuery();
//        $sql = "select status, name,id,due_date as dueDate,created_at, description, category, priority as createdAt from todo where userId='rahul' group by status,dueDate,priority order by status,dueDate";
//        return $this->getEntityManager()->getConnection()->query($sql);

        $paginator = new Paginator($qb,false);
        $paginator->setUseOutputWalkers(false);
        return $paginator;
//        return $query->execute();
    }
}
